kind: source
spec:
  name: "aws"
  path: "cloudquery/aws"
  registry: "cloudquery"
  version: "v22.18.0"
  tables: [
    "aws_accessanalyzer_analyzer_findings",
    "aws_accessanalyzer_analyzers",
    "aws_appconfig_deployment_strategies",
    "aws_apprunner_auto_scaling_configurations",
    "aws_apprunner_observability_configurations",
    "aws_athena_data_catalogs",
    "aws_athena_work_groups",
    "aws_cloudfront_cache_policies",
    "aws_cloudtrail_trails",
    "aws_cloudwatch_alarms",
    "aws_cloudwatchlogs_metric_filters",
    "aws_docdb_certificates",
    "aws_ec2_ebs_volumes",
    "aws_ec2_flow_logs",
    "aws_ec2_instances",
    "aws_ec2_instance_statuses",
    "aws_ec2_internet_gateways",
    "aws_ec2_key_pairs",
    "aws_ec2_managed_prefix_lists",
    "aws_ec2_nat_gateways",
    "aws_ec2_network_acls",
    "aws_ec2_network_interfaces",
    "aws_ec2_regional_configs",
    "aws_ec2_route_tables",
    "aws_ec2_security_groups",
    "aws_ec2_subnets",
    "aws_ec2_vpc_endpoints",
    "aws_ec2_vpcs",
    "aws_eventbridge_event_buses",
    "aws_iam_credential_reports",
    "aws_iam_groups",
    "aws_iam_password_policies",
    "aws_iam_policies",
    "aws_iam_roles",
    "aws_iam_saml_identity_providers",
    "aws_iam_server_certificates",
    "aws_iam_user_groups",
    "aws_iam_users",
    "aws_iam_virtual_mfa_devices",
    "aws_kms_aliases",
    "aws_kms_keys",
    "aws_organizations",
    "aws_rds_certificates",
    "aws_rds_db_parameter_groups",
    "aws_rds_db_security_groups",
    "aws_rds_instances",
    "aws_rds_option_groups",
    "aws_regions",
    "aws_resiliencehub_suggested_resiliency_policies",
    "aws_route53resolver_firewall_domain_lists",
    "aws_route53resolver_resolver_rules",
    "aws_s3_buckets",
    "aws_scheduler_schedule_groups",
    "aws_securityhub_hubs",
    "aws_sns_subscriptions",
    "aws_xray_groups",
    "aws_xray_sampling_rules",
  ]
  destinations: ["postgresql"]
  spec:
    regions: ["us-east-2"]
